title: Samuel O. John-Maxwell
logo: /assets/corporate-photo.jpg
description: Guided by curiosity, I contribute to organizations by creating impact through leveraging data, systems, and strong collaboration with subject matter experts and stakeholders.
show_downloads: false
theme: jekyll-theme-minimal
